from tests.test_graphs import DIRECTED_Set1_A, DIRECTED_H_3X3_Simple, DIRECTED_Set1_A_SUPERNODE, DIRECTED_Set1_I_SUPERNODE, \
    DIRECTED_Set1_B_CS, DIRECTED_Set1_C_VSandCS, DIRECTED_Set1_F_MULTIPLE_VSandCS, DIRECTED_Set1_E_MULTIPLE_VSandCS, \
    DIRECTED_Set1_I_NOOR